export const CART_ACTION_TYPES = {
    'SET_OPEN': 'cart/SET_OPEN',
    'SET_ITEMS': 'cart/SET_ITEMS',
    // 'INCREASE_ITEM_QUANTITY': 'cart/INCREASE_ITEM_QUANTITY',
    // 'DECREASE_ITEM_QUANTITY': 'cart/DECREASE_ITEM_QUANTITY',
    // 'REMOVE_ITEM': 'cart/REMOVE_ITEM',
}